# Generated by Django 5.2.8 on 2026-05-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("AppointmentID", models.AutoField(primary_key=True, serialize=False)),
                ("DoctorID", models.CharField(max_length=10)),
                ("PatientID", models.CharField(max_length=10)),
                ("AppointmentDate", models.DateField()),
                ("AppointmentTime", models.TimeField()),
            ],
            options={
                "db_table": "Appointments",
            },
        ),
    ]
