# Generated by Django 5.2.8 on 2026-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "PatientID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("FullName", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Patients",
            },
        ),
    ]
